### ISSUE TITLE
slice offset bug in CT series viewing

### ISSUE THREAD

**Issue by charleswg** [box-dicom/box-dicom.github.io#12]
It's CT specific, not happening for MRI.

Viewing multiple image series and the displayed slices are inconsistent (e.g. image, instance number, slice number) depends on which panel the user clicked on.

To reproduce the problem, drag the same series in multiple panel. Click on each and see the discrepancies on different panels.

**Comment by charleswg** [comment]
An online example from your own: https://codepen.io/box-platform/pen/VbPvNb

Note that if you clicked on top left panel (the location is the same as top right panel), the image number is different.  You can swap in with identical series and the image number offset is there still.

**Comment by charleswg** [comment]
Going to tag @mickr and hope this issue is getting the right attention.

**Comment by mickr** [comment]
@jstoffan should be made aware of this.

**Comment by charleswg** [comment]
Any update to this issues? It's critical as it's an FDA approved product.

**Comment by charleswg** [comment]
ping @jstoffan

**Comment by cweeii** [comment]
Hi @charleswg, apologies for the many long months this took.  We've released a fix to address this today.  Please take a look and let us know if the issue has now been resolved for you!

**Comment by charleswg** [comment]
Tested working fine in CT.
